version: '3.9'

services:

# nestjs App
    nestjs-api:
      container_name: nest-api
      extends:
        file: compose.base.yaml
        service: nx-app-base
      # command: nx serve backend --watch --host=0.0.0.0
      command: pnpm run backend:dev:docker
      # command: pnpm run configproxy && nx serve backend --watch --host=0.0.0.0
      # build:
      #   context: .
      #   dockerfile: ../apps/backend/Dockerfile
      #   args:
      #     - POSTGRESQL_URL=${POSTGRESQL_URL}
      ports:
        - 3000:3000
      networks:
          - postgres
      # depends_on:
      #   - postgres
      env_file:
        - .env
      # restart: no
      # tty: true


networks:
    postgres:

volumes:
    postgres:
        name: basedev-db
    pgadmin:
        name: pgadmin-db
    mono-node-modules: null
    # mono-node-modules:
    #     name: mono-node-modules

